package presentation;

import business.Aluno;
import business.Facade;
import business.Troca;
import business.UnidadeCurricular;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 * MenuAluno => Interface do menu principal do Aluno.
 * 
 * @author Carlos Pedrosa
 * @author David Sousa
 * @author Manuel Sousa
 */
public class MenuAluno extends javax.swing.JFrame {

    private Facade facade;

    /**
     * Construtor de um novo LoginFrame.
     * Inicializa os componentes da interface e comunica com a Facade 
     * para saber qual o Aluno em sessão. Depois disto, determina as suas
     * Unidades Curriculares para assim preencher a tabela principal.
     * 
     * @param facade
     */
    public MenuAluno (Facade facade) {
        initComponents();
        this.facade = facade;

        Aluno a = (Aluno)this.facade.getSessao();

        //Adicionar todas as UCs do aluno à tabela do menu.
        DefaultTableModel dtm = (DefaultTableModel)uCTurnoTable.getModel();
        ArrayList<UnidadeCurricular> lUC = this.facade.getAllUCs();
        Map<String, String> turnosAluno = a.getTurnos();

        lUC.forEach(c -> {
            dtm.addRow(new Object[]{
                c.getidUC(),
                c.getNome(),
                turnosAluno.get(c.getidUC())
            });
        });

        //Adicionar Nome e Email do Aluno às respetivas caixas de texto.
        nameTextField.setText(a.getNome());
        emailTextField.setText(a.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        efetuarRegisto_Dialog = new javax.swing.JDialog();
        registarButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaUCs = new javax.swing.JTable();
        trocas_Dialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        efetuarTrocaButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        aceitarTrocaButton = new javax.swing.JButton();
        uc_comboBox_trocas = new javax.swing.JComboBox<>();
        efetuarTroca_Dialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        turnoPretendido = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        turnoAtual = new javax.swing.JTextField();
        validarTrocaButton = new javax.swing.JButton();
        SairButton = new javax.swing.JButton();
        uc_efetuarTroca_TextField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        uCTurnoTable = new javax.swing.JTable();
        loginJPanel5 = new javax.swing.JPanel();
        efetuarRegisto = new javax.swing.JLabel();
        loginJPanel6 = new javax.swing.JPanel();
        removerUC = new javax.swing.JLabel();
        loginJPanel7 = new javax.swing.JPanel();
        trocas = new javax.swing.JLabel();

        efetuarRegisto_Dialog.setTitle("Efetuar Registo numa UC");
        efetuarRegisto_Dialog.setMinimumSize(new java.awt.Dimension(590, 398));
        efetuarRegisto_Dialog.setResizable(false);
        efetuarRegisto_Dialog.setSize(new java.awt.Dimension(590, 398));

        registarButton.setText("Registar");
        registarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarRegistoDialog_registarButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Sair");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarRegistoDialog_exitButtonActionPerformed(evt);
            }
        });

        tabelaUCs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Unidade Curricular", "Turno", "Sala"
            }
        ));
        jScrollPane2.setViewportView(tabelaUCs);

        javax.swing.GroupLayout efetuarRegisto_DialogLayout = new javax.swing.GroupLayout(efetuarRegisto_Dialog.getContentPane());
        efetuarRegisto_Dialog.getContentPane().setLayout(efetuarRegisto_DialogLayout);
        efetuarRegisto_DialogLayout.setHorizontalGroup(
            efetuarRegisto_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(efetuarRegisto_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(efetuarRegisto_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(efetuarRegisto_DialogLayout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registarButton))
                    .addGroup(efetuarRegisto_DialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        efetuarRegisto_DialogLayout.setVerticalGroup(
            efetuarRegisto_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, efetuarRegisto_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(efetuarRegisto_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        trocas_Dialog.setTitle("Trocas Disponíveis");
        trocas_Dialog.setMaximumSize(new java.awt.Dimension(567, 382));
        trocas_Dialog.setMinimumSize(new java.awt.Dimension(567, 382));
        trocas_Dialog.setResizable(false);
        trocas_Dialog.setSize(new java.awt.Dimension(567, 382));
        trocas_Dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                trocas_DialogWindowClosing(evt);
            }
        });

        jLabel1.setText("Unidade Curricular");

        efetuarTrocaButton.setText("Efetuar Troca");
        efetuarTrocaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocasDialog_efetuarTrocaButtonActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idAluno", "Turno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        aceitarTrocaButton.setText("Aceitar Troca");
        aceitarTrocaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trocasDialog_aceitarTrocaButtonActionPerformed(evt);
            }
        });

        uc_comboBox_trocas.setMaximumSize(new java.awt.Dimension(52, 27));
        uc_comboBox_trocas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uc_comboBox_trocasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout trocas_DialogLayout = new javax.swing.GroupLayout(trocas_Dialog.getContentPane());
        trocas_Dialog.getContentPane().setLayout(trocas_DialogLayout);
        trocas_DialogLayout.setHorizontalGroup(
            trocas_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trocas_DialogLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(trocas_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(trocas_DialogLayout.createSequentialGroup()
                        .addComponent(efetuarTrocaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceitarTrocaButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trocas_DialogLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uc_comboBox_trocas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        trocas_DialogLayout.setVerticalGroup(
            trocas_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trocas_DialogLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(trocas_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uc_comboBox_trocas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(trocas_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(efetuarTrocaButton)
                    .addComponent(aceitarTrocaButton))
                .addGap(31, 31, 31))
        );

        efetuarTroca_Dialog.setTitle("Efetuar Troca");
        efetuarTroca_Dialog.setMinimumSize(new java.awt.Dimension(466, 305));
        efetuarTroca_Dialog.setResizable(false);
        efetuarTroca_Dialog.setSize(new java.awt.Dimension(466, 305));
        efetuarTroca_Dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                efetuarTroca_DialogWindowClosing(evt);
            }
        });

        jLabel2.setText("Unidade Curricular");

        jLabel6.setText("Turno Pretendido");

        jLabel8.setText("Turno Atual");

        turnoAtual.setEditable(false);

        validarTrocaButton.setText("Validar");
        validarTrocaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarTrocaDialog_validarTrocaButtonActionPerformed(evt);
            }
        });

        SairButton.setText("Sair");
        SairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarTrocaDialog_SairButtonActionPerformed(evt);
            }
        });

        uc_efetuarTroca_TextField.setEditable(false);

        javax.swing.GroupLayout efetuarTroca_DialogLayout = new javax.swing.GroupLayout(efetuarTroca_Dialog.getContentPane());
        efetuarTroca_Dialog.getContentPane().setLayout(efetuarTroca_DialogLayout);
        efetuarTroca_DialogLayout.setHorizontalGroup(
            efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, efetuarTroca_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(efetuarTroca_DialogLayout.createSequentialGroup()
                        .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(efetuarTroca_DialogLayout.createSequentialGroup()
                                .addGap(204, 266, Short.MAX_VALUE)
                                .addComponent(validarTrocaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(efetuarTroca_DialogLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(turnoAtual))))
                    .addGroup(efetuarTroca_DialogLayout.createSequentialGroup()
                        .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uc_efetuarTroca_TextField)
                            .addComponent(turnoPretendido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        efetuarTroca_DialogLayout.setVerticalGroup(
            efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(efetuarTroca_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uc_efetuarTroca_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoPretendido, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(efetuarTroca_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(validarTrocaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGT - Menu Aluno");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Serviço de Gestão de Turnos");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sgt_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        nameTextField.setEditable(false);
        nameTextField.setToolTipText("");
        nameTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Email");

        emailTextField.setEditable(false);
        emailTextField.setToolTipText("");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        uCTurnoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código UC", "Unidade Curricular", "Turno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(uCTurnoTable);

        loginJPanel5.setBackground(new java.awt.Color(102, 0, 102));

        efetuarRegisto.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        efetuarRegisto.setForeground(new java.awt.Color(255, 255, 255));
        efetuarRegisto.setText("Efetuar Registo");
        efetuarRegisto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                efetuarRegistoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginJPanel5Layout = new javax.swing.GroupLayout(loginJPanel5);
        loginJPanel5.setLayout(loginJPanel5Layout);
        loginJPanel5Layout.setHorizontalGroup(
            loginJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(efetuarRegisto)
                .addGap(9, 9, 9))
        );
        loginJPanel5Layout.setVerticalGroup(
            loginJPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(efetuarRegisto, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        loginJPanel6.setBackground(new java.awt.Color(102, 0, 102));
        loginJPanel6.setPreferredSize(new java.awt.Dimension(127, 48));

        removerUC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        removerUC.setForeground(new java.awt.Color(255, 255, 255));
        removerUC.setText("Remover UC");
        removerUC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerUCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginJPanel6Layout = new javax.swing.GroupLayout(loginJPanel6);
        loginJPanel6.setLayout(loginJPanel6Layout);
        loginJPanel6Layout.setHorizontalGroup(
            loginJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanel6Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(removerUC)
                .addGap(20, 20, 20))
        );
        loginJPanel6Layout.setVerticalGroup(
            loginJPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removerUC, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        loginJPanel7.setBackground(new java.awt.Color(102, 0, 102));
        loginJPanel7.setPreferredSize(new java.awt.Dimension(127, 48));
        loginJPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                trocasMousePressed(evt);
            }
        });

        trocas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        trocas.setForeground(new java.awt.Color(255, 255, 255));
        trocas.setText("Trocas");

        javax.swing.GroupLayout loginJPanel7Layout = new javax.swing.GroupLayout(loginJPanel7);
        loginJPanel7.setLayout(loginJPanel7Layout);
        loginJPanel7Layout.setHorizontalGroup(
            loginJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(trocas)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        loginJPanel7Layout.setVerticalGroup(
            loginJPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trocas, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
                                    .addComponent(emailTextField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(loginJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(loginJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginJPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {loginJPanel5, loginJPanel6});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método que efetua o registo numa UC.
     * Este método trata de comunicar a Facade que uma nova UC vai ser registada.
     * Aqui também é adicionada a informação dessa nova UC à tabela principal.
     * 
     * @param evt 
     */
    private void efetuarRegistoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efetuarRegistoMouseClicked
        efetuarRegisto_Dialog.setVisible(true);
        efetuarRegisto_Dialog.setLocationRelativeTo(this);

        //Preencher tabela do JDialog efetuarRegisto_Dialog.
        DefaultTableModel uc_dtm  = (DefaultTableModel)tabelaUCs.getModel();
        ArrayList<UnidadeCurricular> ucs = this.facade.getAll();

        ucs.forEach(uc -> {
            uc.getTurnos().forEach(t -> {
                uc_dtm.addRow(new Object[] {
                    "[" + uc.getidUC() + "]" + " " + uc.getNome(),
                    t.getTipo(),
                    t.getSala()
                });
            });
        });
    }//GEN-LAST:event_efetuarRegistoMouseClicked
    
    /**
     * Método que comunica que uma UC foi removida.
     * Aqui é feito o código para remover a UC selecionada da tabela.
     * Depois, é comunicado à Facade, para esta efetuar as devidas alterações.
     * 
     * @param evt 
     */
    private void removerUCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerUCMouseClicked
        try {
            int index = uCTurnoTable.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel)uCTurnoTable.getModel();
            String nomeUC = (String)dtm.getValueAt(index, 0);
            String tipoTurno = (String)dtm.getValueAt(index, 2);
            this.facade.unsubscribeUC(nomeUC, tipoTurno);

            //Código para tirar disciplina da tabela ucTurnoTable.
            dtm.removeRow(index);
        } catch (ArrayIndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma Unidade Curricular Selecionada!", "Remover UC", 0);
        }
    }//GEN-LAST:event_removerUCMouseClicked
    
    /**
     * Método que invoca o JDialog trocas_Dialog.
     * Depois de este ser chamado, é preenchida a tabela com todas as trocas 
     * disponíveis de uma determinada UC que é selecionada.
     * 
     * @param evt 
     */
    private void trocasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trocasMousePressed
        ArrayList<UnidadeCurricular> lUC = this.facade.getAllUCs();
        if (!lUC.isEmpty()) {
            trocas_Dialog.setVisible(true);
            trocas_Dialog.setLocationRelativeTo(this);
            //uc_comboBox_trocas.removeAllItems();
                
            lUC.forEach(uc -> {
                uc_comboBox_trocas.addItem(uc.getidUC() + " - " + uc.getNome());
            });
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma UC Registada!", "Trocas", 0);
        }
    }//GEN-LAST:event_trocasMousePressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        LoginFrame lf = new LoginFrame(facade);
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    /**
     * Métodos do JDialog efetuarRegisto_Dialog.
     */
    private void efetuarRegistoDialog_registarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarRegistoDialog_registarButtonActionPerformed
        int index = tabelaUCs.getSelectedRow();
        String nomeUC = (String)tabelaUCs.getValueAt(index, 0);
        String idUC = nomeUC.substring(nomeUC.indexOf("[") + 1, nomeUC.indexOf("]"));
        String tipoTurno = (String)tabelaUCs.getValueAt(index, 1);

        boolean flag = this.facade.subscribeUC(idUC, tipoTurno);
        if (!flag)
            javax.swing.JOptionPane.showMessageDialog(this, "Já se encontra registado nessa UC.", "Registo UC", 0);
        else {
            DefaultTableModel dtm = (DefaultTableModel)uCTurnoTable.getModel();
            dtm.addRow(new Object[] {
                idUC,
                nomeUC.substring(nomeUC.indexOf("]") + 2),
                tipoTurno
            });

            /* Actualizar Map<idUC, tipoTurno> com UC que foi registada. */
            Aluno a = (Aluno)this.facade.getSessao();
            Map<String, String> turnos = a.getTurnos();
            turnos.put(idUC, tipoTurno);
            a.setTurnos(turnos);

            javax.swing.JOptionPane.showMessageDialog(this, "Registo efetuado com sucesso!", "Registo UC", 1);
        }

        //uc_comboBox_trocas.addItem(idUC + " - " + nomeUC);
    }//GEN-LAST:event_efetuarRegistoDialog_registarButtonActionPerformed

    private void efetuarRegistoDialog_exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarRegistoDialog_exitButtonActionPerformed
        efetuarRegisto_Dialog.setVisible(false);
    }//GEN-LAST:event_efetuarRegistoDialog_exitButtonActionPerformed


    /**
     * Métodos do JDialog trocas_Dialog.
     */
    
    /**
     * Método de action performed no menu trocas.
     * Este método que comunica à Facade que uma troca foi aceite.
     * Posto isto, adiciona esse novo turno ao menu principal do Aluno.
     * 
     * @param evt 
     */
    private void trocasDialog_aceitarTrocaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocasDialog_aceitarTrocaButtonActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
        int index = jTable2.getSelectedRow();
        String tipoTurnoPretendido = (String)dtm.getValueAt(index, 1);
        Integer idAlunoReq = (Integer)dtm.getValueAt(index, 0);
        String uc = (String)uc_comboBox_trocas.getSelectedItem();
        String idUC = uc.substring(0, uc.indexOf(" "));
        
        this.facade.resolverTrocaAluno(idAlunoReq, idUC, tipoTurnoPretendido);
                        
        /* Mudar Turno no Menu do Aluno após uma Troca. */
        DefaultTableModel dtm2 = (DefaultTableModel)uCTurnoTable.getModel();
        boolean flag = true;
        for (int i = 0; i < dtm2.getRowCount() && flag; i++) {
            String idUCTabela = (String)dtm2.getValueAt(i, 0);
            if (idUCTabela.equals(idUC)) {
                dtm2.setValueAt(tipoTurnoPretendido, i, 2);
                flag = false;
            }
        }
        
        /* Remove a troca da tabela. */
        dtm.removeRow(index);
    }//GEN-LAST:event_trocasDialog_aceitarTrocaButtonActionPerformed

    private void trocasDialog_efetuarTrocaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trocasDialog_efetuarTrocaButtonActionPerformed
        efetuarTroca_Dialog.setVisible(true);
        efetuarTroca_Dialog.setLocationRelativeTo(this);

        String uc = (String)uc_comboBox_trocas.getSelectedItem();
        uc_efetuarTroca_TextField.setText(uc);

        String idUC = uc.substring(0, uc.indexOf(" "));
        Aluno a = (Aluno)this.facade.getSessao();
        String turno = a.getTurnos().get(idUC);
        turnoAtual.setText(turno);

        ArrayList<String> tipoTurnos = this.facade.getTurnosUC(idUC);
        tipoTurnos.remove(turno); //Remove o turno em que o aluno está inserido.
        tipoTurnos.forEach(s -> {
            turnoPretendido.addItem(s);
        });
    }//GEN-LAST:event_trocasDialog_efetuarTrocaButtonActionPerformed

    private void trocas_DialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_trocas_DialogWindowClosing
        uc_comboBox_trocas.removeAllItems();
    }//GEN-LAST:event_trocas_DialogWindowClosing


    /**
     * Métodos do JDialog efetuarTroca_Dialog.
     */
    private void efetuarTrocaDialog_validarTrocaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarTrocaDialog_validarTrocaButtonActionPerformed
        String uc = uc_efetuarTroca_TextField.getText();
        String idUC = uc.substring(0, uc.indexOf(" "));
        String turnoActual = turnoAtual.getText();
        String turnoPret = (String)turnoPretendido.getSelectedItem();
        
        int flag = this.facade.resolveTrocaAluno(idUC, turnoActual, turnoPret);
        
        if (flag == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro. Turno está cheio.", "Troca de Turno", 0);
        } else {
           turnoPretendido.removeAllItems();
           efetuarTroca_Dialog.setVisible(false); 
        }
    }//GEN-LAST:event_efetuarTrocaDialog_validarTrocaButtonActionPerformed

    private void efetuarTrocaDialog_SairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarTrocaDialog_SairButtonActionPerformed
        turnoPretendido.removeAllItems();
        efetuarTroca_Dialog.setVisible(false);
    }//GEN-LAST:event_efetuarTrocaDialog_SairButtonActionPerformed

    private void uc_comboBox_trocasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uc_comboBox_trocasActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)jTable2.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) dtm.removeRow(i);
        String uc = (String)uc_comboBox_trocas.getSelectedItem();
        try {
            String idUC = uc.substring(0, uc.indexOf(" "));
            Aluno a = (Aluno)this.facade.getSessao();
            String turnoAtual = a.getTurnos().get(idUC);
        
            ArrayList<Troca> trocas = this.facade.getTrocasUC(turnoAtual, idUC);
            trocas.forEach(t -> {
                dtm.addRow(new Object[] {
                    t.getAlunoReq(),
                    t.getTurnoAtual()
                });
            });
        } catch (NullPointerException e) { }
    }//GEN-LAST:event_uc_comboBox_trocasActionPerformed

    private void efetuarTroca_DialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_efetuarTroca_DialogWindowClosing
        turnoPretendido.removeAllItems();
    }//GEN-LAST:event_efetuarTroca_DialogWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SairButton;
    private javax.swing.JButton aceitarTrocaButton;
    private javax.swing.JLabel efetuarRegisto;
    private javax.swing.JDialog efetuarRegisto_Dialog;
    private javax.swing.JButton efetuarTrocaButton;
    private javax.swing.JDialog efetuarTroca_Dialog;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel loginJPanel5;
    private javax.swing.JPanel loginJPanel6;
    private javax.swing.JPanel loginJPanel7;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton registarButton;
    private javax.swing.JLabel removerUC;
    private javax.swing.JTable tabelaUCs;
    private javax.swing.JLabel trocas;
    private javax.swing.JDialog trocas_Dialog;
    private javax.swing.JTextField turnoAtual;
    private javax.swing.JComboBox<String> turnoPretendido;
    private javax.swing.JTable uCTurnoTable;
    private javax.swing.JComboBox<String> uc_comboBox_trocas;
    private javax.swing.JTextField uc_efetuarTroca_TextField;
    private javax.swing.JButton validarTrocaButton;
    // End of variables declaration//GEN-END:variables
}
