/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.CapMaxeNenhumComFaltasException;
import business.Docente;
import business.Facade;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 * MenuDocente => Interface do menu principal do Docente. 
 * 
 * @author Carlos Pedrosa
 * @author David Sousa
 * @author Manuel Sousa
 */
public class MenuDocente extends javax.swing.JFrame {

    private Facade facade;

    /**
     * Construtor de um novo MenuDocente.
     * 
     * @param facade
     */
    public MenuDocente (Facade facade) {
        initComponents();
        this.facade = facade;

        Docente d = (Docente)this.facade.getSessao();
        nomeTextField.setText(d.getNome());
        emailTextField.setText(d.getUsername());
        ucTextField.setText(d.getidUC());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registarUC_Dialog = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        UCaRegistar = new javax.swing.JTextField();
        registarUCButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        qtsTurnos = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        idUCaRegistar = new javax.swing.JTextField();
        nAulasPrev = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        consultarTurno_Dialog = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        capacidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        consultarTurnoTable = new javax.swing.JTable();
        sairButton = new javax.swing.JButton();
        addFaltaButton = new javax.swing.JButton();
        capacidadeButton = new javax.swing.JButton();
        turnoComboBox = new javax.swing.JComboBox<>();
        efetuarTrocaDocente_Dialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        alunoPretendido = new javax.swing.JTextField();
        trocarButton = new javax.swing.JButton();
        sair2Button = new javax.swing.JButton();
        turnoPretendido = new javax.swing.JComboBox<>();
        newCapacity = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        newCapacidade = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        alterarCapacidadeButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ucTextField = new javax.swing.JTextField();
        loginJPanel1 = new javax.swing.JPanel();
        consultarTurno_Label = new javax.swing.JLabel();
        loginJPanel3 = new javax.swing.JPanel();
        efetuarTroca = new javax.swing.JLabel();
        loginJPanel4 = new javax.swing.JPanel();
        registarUC_Label = new javax.swing.JLabel();

        registarUC_Dialog.setTitle("Registar UC");
        registarUC_Dialog.setMinimumSize(new java.awt.Dimension(366, 102));
        registarUC_Dialog.setResizable(false);
        registarUC_Dialog.setSize(new java.awt.Dimension(405, 174));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Unidade Curricular");

        registarUCButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        registarUCButton.setText("Registar");
        registarUCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarUCDialog_registarButtonActionPerformed(evt);
            }
        });

        closeButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        closeButton.setForeground(new java.awt.Color(255, 0, 0));
        closeButton.setText("Sair");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarUCDialog_closeButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Turnos Pretendidos");

        qtsTurnos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("ID U. Curricular");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Aulas Previstas");

        javax.swing.GroupLayout registarUC_DialogLayout = new javax.swing.GroupLayout(registarUC_Dialog.getContentPane());
        registarUC_Dialog.getContentPane().setLayout(registarUC_DialogLayout);
        registarUC_DialogLayout.setHorizontalGroup(
            registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registarUC_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registarUC_DialogLayout.createSequentialGroup()
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                        .addComponent(registarUCButton))
                    .addGroup(registarUC_DialogLayout.createSequentialGroup()
                        .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idUCaRegistar)
                            .addComponent(UCaRegistar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registarUC_DialogLayout.createSequentialGroup()
                                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(nAulasPrev)
                                    .addComponent(qtsTurnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        registarUC_DialogLayout.setVerticalGroup(
            registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registarUC_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UCaRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(idUCaRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtsTurnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nAulasPrev)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registarUC_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(registarUCButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        consultarTurno_Dialog.setTitle("Consultar Turno");
        consultarTurno_Dialog.setMinimumSize(new java.awt.Dimension(721, 400));
        consultarTurno_Dialog.setResizable(false);
        consultarTurno_Dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                consultarTurno_DialogWindowClosing(evt);
            }
        });

        jLabel8.setText("Turno");

        jLabel11.setText("Capacidade");

        capacidade.setEditable(false);

        consultarTurnoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Aluno", "Nome", "Faltas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(consultarTurnoTable);

        sairButton.setText("Sair");
        sairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTurnoDialog_sairButtonActionPerformed(evt);
            }
        });

        addFaltaButton.setText("Add Falta");
        addFaltaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTurnoDialog_addFaltaButtonActionPerformed(evt);
            }
        });

        capacidadeButton.setText("Capacidade");
        capacidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarTurnoDialog_capacidadeButtonActionPerformed(evt);
            }
        });

        turnoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnoComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultarTurno_DialogLayout = new javax.swing.GroupLayout(consultarTurno_Dialog.getContentPane());
        consultarTurno_Dialog.getContentPane().setLayout(consultarTurno_DialogLayout);
        consultarTurno_DialogLayout.setHorizontalGroup(
            consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarTurno_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultarTurno_DialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(capacidadeButton))
                    .addGroup(consultarTurno_DialogLayout.createSequentialGroup()
                        .addGroup(consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addGroup(consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(consultarTurno_DialogLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(consultarTurno_DialogLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(turnoComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(consultarTurno_DialogLayout.createSequentialGroup()
                        .addComponent(sairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addFaltaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        consultarTurno_DialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addFaltaButton, sairButton});

        consultarTurno_DialogLayout.setVerticalGroup(
            consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultarTurno_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(capacidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(capacidadeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(consultarTurno_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sairButton)
                    .addComponent(addFaltaButton))
                .addContainerGap())
        );

        efetuarTrocaDocente_Dialog.setTitle("Efetuar Troca");
        efetuarTrocaDocente_Dialog.setMinimumSize(new java.awt.Dimension(305, 172));
        efetuarTrocaDocente_Dialog.setResizable(false);

        jLabel12.setText("Turno Pretendido");

        jLabel13.setText("Aluno Pretendido");

        trocarButton.setText("Trocar");
        trocarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarTrocaDocenteDialog_trocarButtonActionPerformed(evt);
            }
        });

        sair2Button.setText("Sair");
        sair2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarTrocaDocenteDialog_sair2ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout efetuarTrocaDocente_DialogLayout = new javax.swing.GroupLayout(efetuarTrocaDocente_Dialog.getContentPane());
        efetuarTrocaDocente_Dialog.getContentPane().setLayout(efetuarTrocaDocente_DialogLayout);
        efetuarTrocaDocente_DialogLayout.setHorizontalGroup(
            efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(efetuarTrocaDocente_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(efetuarTrocaDocente_DialogLayout.createSequentialGroup()
                        .addGroup(efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alunoPretendido, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(turnoPretendido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(efetuarTrocaDocente_DialogLayout.createSequentialGroup()
                        .addComponent(sair2Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                        .addComponent(trocarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        efetuarTrocaDocente_DialogLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {sair2Button, trocarButton});

        efetuarTrocaDocente_DialogLayout.setVerticalGroup(
            efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(efetuarTrocaDocente_DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(turnoPretendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alunoPretendido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(efetuarTrocaDocente_DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sair2Button)
                    .addComponent(trocarButton))
                .addContainerGap())
        );

        newCapacity.setTitle("Nova Capacidade");
        newCapacity.setMinimumSize(new java.awt.Dimension(196, 93));
        newCapacity.setResizable(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Insira Nova Capacidade:");

        jButton1.setText("Sair");

        alterarCapacidadeButton.setText("Alterar");
        alterarCapacidadeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarCapacidadeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newCapacityLayout = new javax.swing.GroupLayout(newCapacity.getContentPane());
        newCapacity.getContentPane().setLayout(newCapacityLayout);
        newCapacityLayout.setHorizontalGroup(
            newCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCapacityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(newCapacityLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(alterarCapacidadeButton))
                    .addComponent(newCapacidade))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        newCapacityLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {alterarCapacidadeButton, jButton1});

        newCapacityLayout.setVerticalGroup(
            newCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newCapacityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newCapacityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alterarCapacidadeButton)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        newCapacityLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {alterarCapacidadeButton, jButton1});

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SGT - Menu Docente");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Serviço de Gestão de Turnos");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sgt_logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        nomeTextField.setEditable(false);
        nomeTextField.setToolTipText("");
        nomeTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("Email");

        emailTextField.setEditable(false);
        emailTextField.setToolTipText("");
        emailTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setText("UC");

        ucTextField.setEditable(false);
        ucTextField.setToolTipText("");
        ucTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        loginJPanel1.setBackground(new java.awt.Color(102, 0, 102));

        consultarTurno_Label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        consultarTurno_Label.setForeground(new java.awt.Color(255, 255, 255));
        consultarTurno_Label.setText("Consultar Turno");
        consultarTurno_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarTurno_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginJPanel1Layout = new javax.swing.GroupLayout(loginJPanel1);
        loginJPanel1.setLayout(loginJPanel1Layout);
        loginJPanel1Layout.setHorizontalGroup(
            loginJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultarTurno_Label)
                .addGap(9, 9, 9))
        );
        loginJPanel1Layout.setVerticalGroup(
            loginJPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(consultarTurno_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        loginJPanel3.setBackground(new java.awt.Color(102, 0, 102));

        efetuarTroca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        efetuarTroca.setForeground(new java.awt.Color(255, 255, 255));
        efetuarTroca.setText("Efetuar Troca");
        efetuarTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                efetuarTrocaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginJPanel3Layout = new javax.swing.GroupLayout(loginJPanel3);
        loginJPanel3.setLayout(loginJPanel3Layout);
        loginJPanel3Layout.setHorizontalGroup(
            loginJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(efetuarTroca)
                .addGap(9, 9, 9))
        );
        loginJPanel3Layout.setVerticalGroup(
            loginJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(efetuarTroca, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        loginJPanel4.setBackground(new java.awt.Color(102, 0, 102));

        registarUC_Label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        registarUC_Label.setForeground(new java.awt.Color(255, 255, 255));
        registarUC_Label.setText("Registar UC");
        registarUC_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registarUC_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginJPanel4Layout = new javax.swing.GroupLayout(loginJPanel4);
        loginJPanel4.setLayout(loginJPanel4Layout);
        loginJPanel4Layout.setHorizontalGroup(
            loginJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginJPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registarUC_Label)
                .addGap(9, 9, 9))
        );
        loginJPanel4Layout.setVerticalGroup(
            loginJPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registarUC_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTextField)
                            .addComponent(nomeTextField)
                            .addComponent(ucTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(loginJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(loginJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(loginJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ucTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginJPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginJPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Métodos do MenuDocente.
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        LoginFrame lf = new LoginFrame(facade);
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void registarUC_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registarUC_LabelMouseClicked
        registarUC_Dialog.setVisible(true);
        registarUC_Dialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_registarUC_LabelMouseClicked

    private void consultarTurno_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarTurno_LabelMouseClicked
        consultarTurno_Dialog.setVisible(true);
        consultarTurno_Dialog.setLocationRelativeTo(this);

        Docente d = (Docente)this.facade.getSessao();
        ArrayList<String> turnos = this.facade.getTurnosUC(d.getidUC());
        
        turnos.forEach(t -> {
            turnoComboBox.addItem(t);
        });
    }//GEN-LAST:event_consultarTurno_LabelMouseClicked

    private void efetuarTrocaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_efetuarTrocaMouseClicked
        turnoPretendido.removeAllItems();
        efetuarTrocaDocente_Dialog.setVisible(true);
        efetuarTrocaDocente_Dialog.setLocationRelativeTo(this);

        Docente d = (Docente)this.facade.getSessao();
        ArrayList<String> turnos = this.facade.getTurnosUC(d.getidUC());

        turnos.forEach(t -> {
            turnoPretendido.addItem(t);
        });
    }//GEN-LAST:event_efetuarTrocaMouseClicked

    private void alterarCapacidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarCapacidadeButtonActionPerformed
        Integer newCapacidad = Integer.parseInt(newCapacidade.getText());
        String tipoTurno = (String)turnoComboBox.getSelectedItem();
        this.facade.alteraCapacidade(tipoTurno, newCapacidad);
        
        capacidade.setText(newCapacidad + "");
        
        newCapacity.setVisible(false);
    }//GEN-LAST:event_alterarCapacidadeButtonActionPerformed


    /**
     * Métodos do JDialog registarUC_Dialog.
     */
    private void registarUCDialog_registarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarUCDialog_registarButtonActionPerformed
        String nomeUC = UCaRegistar.getText();
        String idUC = idUCaRegistar.getText();
        int nAulasPrevistas = Integer.parseInt(nAulasPrev.getText());
        int nTurnos = Integer.parseInt((String)qtsTurnos.getSelectedItem());

        boolean flag = this.facade.registaUC(idUC, nomeUC, nTurnos, nAulasPrevistas);

        if (flag)
            javax.swing.JOptionPane.showMessageDialog(registarUC_Dialog, "Unidade Curricular registada com sucesso!", "Registo nova UC", 1);
        else
            javax.swing.JOptionPane.showMessageDialog(registarUC_Dialog, "Unidade Curricular já existente!", "Registo nova UC", 0);
    }//GEN-LAST:event_registarUCDialog_registarButtonActionPerformed

    private void registarUCDialog_closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarUCDialog_closeButtonActionPerformed
        registarUC_Dialog.setVisible(false);
    }//GEN-LAST:event_registarUCDialog_closeButtonActionPerformed


    /**
     * Métodos do JDialog consultarTurno_Dialog.
     */
    private void consultarTurnoDialog_capacidadeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTurnoDialog_capacidadeButtonActionPerformed
        newCapacity.setVisible(true);
        newCapacity.setLocationRelativeTo(null);
    }//GEN-LAST:event_consultarTurnoDialog_capacidadeButtonActionPerformed

    private void consultarTurnoDialog_addFaltaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTurnoDialog_addFaltaButtonActionPerformed
        consultarTurnoTable.removeAll();
        try {
            int index = consultarTurnoTable.getSelectedRow();
            DefaultTableModel dtm = (DefaultTableModel)consultarTurnoTable.getModel();
            Integer idAluno = (Integer)dtm.getValueAt(index, 0);
            String faltaS = (String)dtm.getValueAt(index,2);
            int falta = Integer.parseInt(faltaS);
            String tipoTurno = (String)turnoComboBox.getSelectedItem();
            Docente d  = (Docente)this.facade.getSessao();
            String idUC = d.getidUC();
            this.facade.adicionafalta(idAluno, idUC, tipoTurno, falta + 1);
            dtm.setValueAt(falta + "", index, 2);
            javax.swing.JOptionPane.showMessageDialog(consultarTurno_Dialog, "Falta adicionada com sucesso.", "Marcação de Falta", 1);
        } catch (ArrayIndexOutOfBoundsException e) {
            javax.swing.JOptionPane.showMessageDialog(consultarTurno_Dialog, "Nenhum Aluno selecionado!", "Marcação de Falta", 0);
        } 
    }//GEN-LAST:event_consultarTurnoDialog_addFaltaButtonActionPerformed

    private void turnoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnoComboBoxActionPerformed
        DefaultTableModel dtm = (DefaultTableModel)consultarTurnoTable.getModel();
        for (int i = dtm.getRowCount() - 1; i >= 0; i--) {dtm.removeRow(i);}
        Docente d = (Docente)this.facade.getSessao();
        String idUC = d.getidUC();
        String tipoTurno = (String)turnoComboBox.getSelectedItem();
        Map<Integer, String[]> faltasTurno = this.facade.getFaltasAlunos(tipoTurno, idUC);
                
        faltasTurno.keySet().forEach(idAluno -> {
            String[] info = faltasTurno.get(idAluno);
            dtm.addRow(new Object[] {
                idAluno,
                info[0],
                info[1]
            });
        });
        
        int cap = this.facade.getCapTurno(idUC, tipoTurno);
        capacidade.setText(cap + "");
    }//GEN-LAST:event_turnoComboBoxActionPerformed

    private void consultarTurnoDialog_sairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarTurnoDialog_sairButtonActionPerformed
        turnoComboBox.removeAllItems();
        consultarTurno_Dialog.setVisible(false);
    }//GEN-LAST:event_consultarTurnoDialog_sairButtonActionPerformed

    private void consultarTurno_DialogWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_consultarTurno_DialogWindowClosing
        turnoComboBox.removeAllItems();
        consultarTurno_Dialog.setVisible(false);
    }//GEN-LAST:event_consultarTurno_DialogWindowClosing


    /**
     * Métodos do JDialog efetuarTroca_Docente.
     */
    private void efetuarTrocaDocenteDialog_trocarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarTrocaDocenteDialog_trocarButtonActionPerformed
        int idAluno = Integer.parseInt(alunoPretendido.getText());
        String tipoTurno = (String)turnoPretendido.getSelectedItem();

        try {
            this.facade.trocaAlunoDocente(idAluno,tipoTurno);
        } catch (CapMaxeNenhumComFaltasException e){
            javax.swing.JOptionPane.showMessageDialog(efetuarTrocaDocente_Dialog, "Não foi possível efetuar a Troca", "Efetuar Troca", 1);
        }
    }//GEN-LAST:event_efetuarTrocaDocenteDialog_trocarButtonActionPerformed

    private void efetuarTrocaDocenteDialog_sair2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarTrocaDocenteDialog_sair2ButtonActionPerformed
        efetuarTrocaDocente_Dialog.dispose();
    }//GEN-LAST:event_efetuarTrocaDocenteDialog_sair2ButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField UCaRegistar;
    private javax.swing.JButton addFaltaButton;
    private javax.swing.JButton alterarCapacidadeButton;
    private javax.swing.JTextField alunoPretendido;
    private javax.swing.JTextField capacidade;
    private javax.swing.JButton capacidadeButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JTable consultarTurnoTable;
    private javax.swing.JDialog consultarTurno_Dialog;
    private javax.swing.JLabel consultarTurno_Label;
    private javax.swing.JLabel efetuarTroca;
    private javax.swing.JDialog efetuarTrocaDocente_Dialog;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField idUCaRegistar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel loginJPanel1;
    private javax.swing.JPanel loginJPanel3;
    private javax.swing.JPanel loginJPanel4;
    private javax.swing.JTextField nAulasPrev;
    private javax.swing.JTextField newCapacidade;
    private javax.swing.JDialog newCapacity;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JComboBox<String> qtsTurnos;
    private javax.swing.JButton registarUCButton;
    private javax.swing.JDialog registarUC_Dialog;
    private javax.swing.JLabel registarUC_Label;
    private javax.swing.JButton sair2Button;
    private javax.swing.JButton sairButton;
    private javax.swing.JButton trocarButton;
    private javax.swing.JComboBox<String> turnoComboBox;
    private javax.swing.JComboBox<String> turnoPretendido;
    private javax.swing.JTextField ucTextField;
    // End of variables declaration//GEN-END:variables
}
