insert into Docente (idDocente, username, password, nome, idUC) values (1, 'd1@docentes.uminho.pt', 'JM5Tojse', 'Donall Heffron', 'AL');
insert into Docente (idDocente, username, password, nome, idUC) values (2, 'd2@docentes.uminho.pt', 'c56Buem', 'Isabel Caiado', 'Calc');
insert into Docente (idDocente, username, password, nome, idUC) values (3, 'd3@docentes.uminho.pt', 'NwKPRETO4t', 'Benedict Wehnerr', 'TMD');
insert into Docente (idDocente, username, password, nome, idUC) values (4, 'd4@docentes.uminho.pt', 'hqJMpf', 'Durward Medway', 'PF');
insert into Docente (idDocente, username, password, nome, idUC) values (5, 'd5@docentes.uminho.pt', 'KLUKZKjx', 'Kristina Olenichev', 'EES');
insert into Docente (idDocente, username, password, nome, idUC) values (6, 'd6@docentes.uminho.pt', 'URXOgq', 'Nara Feitosa', 'LI1');
insert into Docente (idDocente, username, password, nome, idUC) values (7, 'd7@docentes.uminho.pt', 'WuXWDDRnVVYC', 'Abbi Benjefield', 'SC');
insert into Docente (idDocente, username, password, nome, idUC) values (8, 'd8@docentes.uminho.pt', 'gAowPM', 'Catharine Kindleside', 'ANALISE');
insert into Docente (idDocente, username, password, nome, idUC) values (9, 'd9@docentes.uminho.pt', 'X7D7mEGJj', 'Suzanna Baldocci', 'TFM');
insert into Docente (idDocente, username, password, nome, idUC) values (10, 'd10@docentes.uminho.pt', 'RPsAQr67', 'Guthrey Nutbrown', 'Log');
insert into Docente (idDocente, username, password, nome, idUC) values (11, 'd11@docentes.uminho.pt', '0sbKvsNGE5', 'Nahum Marieton', 'PI');
insert into Docente (idDocente, username, password, nome, idUC) values (12, 'd12@docentes.uminho.pt', 'vk81U4t3K', 'Darelle McLese', 'LI2');
insert into Docente (idDocente, username, password, nome, idUC) values (13, 'd13@docentes.uminho.pt', 'rn35eK', 'Braden Oleshunin', 'ISD');
insert into Docente (idDocente, username, password, nome, idUC) values (14, 'd14@docentes.uminho.pt', 'cVhconHdBx1', 'Sofia Rodrigues', 'EA');
insert into Docente (idDocente, username, password, nome, idUC) values (15, 'd15@docentes.uminho.pt', 'DZhvWyvGQkZ9', 'Mischa Benasik', 'EE');
insert into Docente (idDocente, username, password, nome, idUC) values (16, 'd16@docentes.uminho.pt', '0M4lCxdSz', 'Weider Donnelly', 'AC');
insert into Docente (idDocente, username, password, nome, idUC) values (17, 'd17@docentes.uminho.pt', 'YufaSHc', 'Nathalia Danit', 'CD');
insert into Docente (idDocente, username, password, nome, idUC) values (18, 'd18@docentes.uminho.pt', 'IziXfs', 'Reinaldos Grey', 'ALG');
insert into Docente (idDocente, username, password, nome, idUC) values (19, 'd19@docentes.uminho.pt', 'bTJb9dBOEjm', 'Frederique Bartoli', 'SO');
insert into Docente (idDocente, username, password, nome, idUC) values (20, 'd20@docentes.uminho.pt', 'MOsDOubTx', 'António Nestor Ribeiro', 'POO');
insert into Docente (idDocente, username, password, nome, idUC) values (21, 'd21@docentes.uminho.pt', 'gZJkJuAIJE', 'Bat Pfleger', 'EM');
insert into Docente (idDocente, username, password, nome, idUC) values (22, 'd22@docentes.uminho.pt', '6eHvpRqRU7k2', 'JNO', 'CP');
insert into Docente (idDocente, username, password, nome, idUC) values (23, 'd23@docentes.uminho.pt', 'j0vLGhgR', 'Vitor Francisco Mendes Gomes Fonte', 'LI3');
insert into Docente (idDocente, username, password, nome, idUC) values (24, 'd24@docentes.uminho.pt', 'j4sIEIK354F', 'Orlando Belo', 'BD');
insert into Docente (idDocente, username, password, nome, idUC) values (25, 'd25@docentes.uminho.pt', 'AGyBLcT', 'Creissac', 'DSS');
insert into Docente (idDocente, username, password, nome, idUC) values (26, 'd26@docentes.uminho.pt', 'dkHWhx7Qs', 'Reta Peppard', 'MDIO');
insert into Docente (idDocente, username, password, nome, idUC) values (27, 'd27@docentes.uminho.pt', 'ZrYnyezLicj', 'Teresa Mallabone', 'SD');
insert into Docente (idDocente, username, password, nome, idUC) values (28, 'd28@docentes.uminho.pt', 'mSR3PjRJP', 'Deana Beetles', 'RC');
insert into Docente (idDocente, username, password, nome, idUC) values (29, 'd29@docentes.uminho.pt', 'GftmApNBcLfe', 'Teresa Monteiro', 'MNOnL');
insert into Docente (idDocente, username, password, nome, idUC) values (30, 'd30@docentes.uminho.pt', 'shqWzK', 'Krissie McClarence', 'SRCR');
insert into Docente (idDocente, username, password, nome, idUC) values (31, 'd31@docentes.uminho.pt', 'TrIE7XKwm9l', 'Cherice Rennox', 'CG');
insert into Docente (idDocente, username, password, nome, idUC) values (32, 'd32@docentes.uminho.pt', 'WE5C7FP1rNYJ', 'Ellwood Gyrgorwicx', 'MEIO');
insert into Docente (idDocente, username, password, nome, idUC) values (33, 'd33@docentes.uminho.pt', 'UrTgja', 'Amos Pinyon', 'CC');
insert into Docente (idDocente, username, password, nome, idUC) values (34, 'd34@docentes.uminho.pt', 'fCjPVDK', 'Georgena Ravenshear', 'PL');
insert into Docente (idDocente, username, password, nome, idUC) values (35, 'd35@docentes.uminho.pt', 'vWMkLu2', 'Norina Debill', 'LI4');
