insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('AL', 'Álgebra Linear EI', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('Calc', 'Cálculo', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('TMD', 'Tópicos de Matemática Discreta', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('PF', 'Programação Funcional', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('EES', 'Elementos de Engenharia de Sistemas', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('LI1', 'Laboratórios de Informática I', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('SC', 'Sistemas de Computação', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('ANALISE', 'Análise', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('TFM', 'Tópicos de Física Moderna', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('Log', 'Lógica EI', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('PI', 'Programação Imperativa', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('LI2', 'Laboratórios de Informática II', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('ISD', 'Introdução aos Sistemas Dinâmicos', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('EA', 'Estatística Aplicada', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('EE', 'Engenharia Económica', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('AC', 'Arquitetura de Computadores', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('CD', 'Comunicação de Dados', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('ALG', 'Algoritmos e Complexidade', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('SO', 'Sistemas Operativos', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('POO', 'Programação Orientada aos Objetos', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('EM', 'Eletromagnetismo EE', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('CP', 'Cálculo de Programas', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('LI3', 'Laboratórios de Informática III', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('BD', 'Bases de Dados', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('DSS', 'Desenvolvimento de Sistemas de Software', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('MDIO', 'Investigação Operacional', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('SD', 'Sistemas Distribuídos', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('RC', 'Redes de Computadores', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('MNOnL', 'Métodos Numéricos e Otimização não Linear', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('SRCR', 'Sistemas de Representação Raciocínio', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('CG', 'Computação Gráfica', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('MEIO', 'Modelos Estocásticos', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('CC', 'Comunicações por Computador', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('PL', 'Processamento de Linguagens', 15);
insert into UnidadeCurricular (idUC, nome, nAulasPrevistas) values ('LI4', 'Laboratórios de Informática IV', 15);
